INSERT INTO languages(name) VALUES ('Английский');
INSERT INTO languages(name) VALUES ('Немецкий');
INSERT INTO languages(name) VALUES ('Французский');
INSERT INTO languages(name) VALUES ('Испанский');
INSERT INTO languages(name) VALUES ('Итальянский');
INSERT INTO languages(name) VALUES ('Китайский');
INSERT INTO languages(name) VALUES ('Японский');

INSERT INTO teachers(firstname, lastname, patronymic) VALUES ('Наталия', 'Орешкина', 'Вячеславовна');
INSERT INTO teachers(firstname, lastname, patronymic) VALUES ('Мария', 'Бочкова', 'Викторовна');
INSERT INTO teachers(firstname, lastname, patronymic) VALUES ('Денис', 'Сидоров', 'Сергеевич');
INSERT INTO teachers(firstname, lastname, patronymic) VALUES ('Сергей', 'Воробьев', 'Максимович');
INSERT INTO teachers(firstname, lastname, patronymic) VALUES ('Дмитрий', 'Кротов', 'Эдуардович');
INSERT INTO teachers(firstname, lastname, patronymic) VALUES ('Дмитрий', 'Песков', 'Александрович');
INSERT INTO teachers(firstname, lastname, patronymic) VALUES ('Алексей', 'Громов', 'Алексеевич');
INSERT INTO teachers(firstname, lastname, patronymic) VALUES ('Андрей', 'Громов', 'Алексеевич');

INSERT INTO courses(name, description, language_id, teacher_id) VALUES ('Базовый английский', 'Основы английского языка для тех, кто никогда не говорил на нем', 1, 2);
INSERT INTO courses(name, description, language_id, teacher_id) VALUES ('Продвинутый английский', 'Если вы уже начинали учить английский язык, но так ни разу и не довели дело до конца, то этот курс для вас!', 1, 4);
INSERT INTO courses(name, description, language_id, teacher_id) VALUES ('Разговорный английский', 'Курс английского для тех, кто хочет улучшить свою речь и научиться говорить правильно', 1, 4);
INSERT INTO courses(name, description, language_id, teacher_id) VALUES ('Немецкий язык', 'Курс по немецкому языку', 2, 1);
INSERT INTO courses(name, description, language_id, teacher_id) VALUES ('Французский язык', 'Курс по французскому языку', 3, 3);
INSERT INTO courses(name, description, language_id, teacher_id) VALUES ('Испанский язык', 'Курс по испанскому языку', 3, 6);
INSERT INTO courses(name, description, language_id, teacher_id) VALUES ('Итальянский язык', 'Курс по итальянскому языку', 5, 5);
INSERT INTO courses(name, description, language_id, teacher_id) VALUES ('Китайский язык', 'Курс по китайскому языку', 6, 8);
INSERT INTO courses(name, description, language_id, teacher_id) VALUES ('Японский язык', 'Курс по японскому языку', 7, 7);

INSERT INTO lessons(course_id, datetime) VALUES (1, to_timestamp('2022-11-01 19:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (1, to_timestamp('2022-11-04 19:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (1, to_timestamp('2022-11-08 19:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (1, to_timestamp('2022-11-11 19:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (1, to_timestamp('2022-11-15 19:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (1, to_timestamp('2022-11-18 19:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (1, to_timestamp('2022-11-22 19:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (1, to_timestamp('2022-11-25 19:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (1, to_timestamp('2022-11-29 19:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (2, to_timestamp('2022-11-01 17:30', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (2, to_timestamp('2022-11-08 17:30', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (2, to_timestamp('2022-11-15 17:30', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (2, to_timestamp('2022-11-22 17:30', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (2, to_timestamp('2022-11-29 17:30', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (3, to_timestamp('2022-11-07 19:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (3, to_timestamp('2022-11-14 19:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (3, to_timestamp('2022-11-21 19:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (3, to_timestamp('2022-11-28 19:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (4, to_timestamp('2022-11-05 12:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (4, to_timestamp('2022-11-12 12:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (4, to_timestamp('2022-11-19 12:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (4, to_timestamp('2022-11-26 12:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (5, to_timestamp('2022-11-03 18:30', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (5, to_timestamp('2022-11-10 18:30', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (5, to_timestamp('2022-11-17 18:30', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (5, to_timestamp('2022-11-24 18:30', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (6, to_timestamp('2022-11-05 15:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (6, to_timestamp('2022-11-12 15:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (6, to_timestamp('2022-11-19 15:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (6, to_timestamp('2022-11-26 15:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (7, to_timestamp('2022-11-05 18:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (7, to_timestamp('2022-11-12 18:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (7, to_timestamp('2022-11-19 18:00', 'YYYY-MM-DD hh24:mi'));
INSERT INTO lessons(course_id, datetime) VALUES (7, to_timestamp('2022-11-26 18:00', 'YYYY-MM-DD hh24:mi'));

INSERT INTO students(firstname, lastname, patronymic) VALUES ('Алексей', 'Демидов', 'Игоревич');
INSERT INTO students(firstname, lastname, patronymic) VALUES ('Ольга', 'Степанова', 'Валерьевна');
INSERT INTO students(firstname, lastname, patronymic) VALUES ('Анна', 'Суматохина', 'Николаевна');
INSERT INTO students(firstname, lastname, patronymic) VALUES ('Глеб', 'Назаренко', 'Сергеевич');
INSERT INTO students(firstname, lastname, patronymic) VALUES ('Игорь', 'Соколов', 'Дмитриевич');
INSERT INTO students(firstname, lastname, patronymic) VALUES ('Елена', 'Булыгина', 'Алексеевна');
INSERT INTO students(firstname, lastname, patronymic) VALUES ('Виталий', 'Демидов', 'Виталиевич');
INSERT INTO students(firstname, lastname, patronymic) VALUES ('Алексей', 'Соколов', 'Андреевич');
INSERT INTO students(firstname, lastname, patronymic) VALUES ('Андрей', 'Бутылкин', 'Петрович');

INSERT INTO students_courses(student_id, course_id) VALUES (1, 2);
INSERT INTO students_courses(student_id, course_id) VALUES (1, 3);
INSERT INTO students_courses(student_id, course_id) VALUES (2, 1);
INSERT INTO students_courses(student_id, course_id) VALUES (3, 1);
INSERT INTO students_courses(student_id, course_id) VALUES (4, 1);
INSERT INTO students_courses(student_id, course_id) VALUES (5, 4);
INSERT INTO students_courses(student_id, course_id) VALUES (6, 5);
INSERT INTO students_courses(student_id, course_id) VALUES (7, 6);
INSERT INTO students_courses(student_id, course_id) VALUES (8, 7);
INSERT INTO students_courses(student_id, course_id) VALUES (9, 7);

INSERT INTO presences(student_id, lesson_id, presence) VALUES (1, 10, true);
INSERT INTO presences(student_id, lesson_id, presence) VALUES (1, 11, true);
INSERT INTO presences(student_id, lesson_id, presence) VALUES (1, 15, true);
INSERT INTO presences(student_id, lesson_id, presence) VALUES (2, 1, true);
INSERT INTO presences(student_id, lesson_id, presence) VALUES (2, 2, true);
INSERT INTO presences(student_id, lesson_id, presence) VALUES (2, 3, false);
INSERT INTO presences(student_id, lesson_id, presence) VALUES (3, 1, true);
INSERT INTO presences(student_id, lesson_id, presence) VALUES (3, 2, true);
INSERT INTO presences(student_id, lesson_id, presence) VALUES (3, 3, false);
INSERT INTO presences(student_id, lesson_id, presence) VALUES (4, 1, true);
INSERT INTO presences(student_id, lesson_id, presence) VALUES (4, 2, false);
INSERT INTO presences(student_id, lesson_id, presence) VALUES (4, 3, false);
INSERT INTO presences(student_id, lesson_id, presence) VALUES (5, 19, true);
INSERT INTO presences(student_id, lesson_id, presence) VALUES (6, 23, true);
INSERT INTO presences(student_id, lesson_id, presence) VALUES (6, 24, true);
INSERT INTO presences(student_id, lesson_id, presence) VALUES (7, 27, false);
INSERT INTO presences(student_id, lesson_id, presence) VALUES (8, 31, false);
INSERT INTO presences(student_id, lesson_id, presence) VALUES (9, 31, true);

INSERT INTO tests(student_id, course_id, topic, score) VALUES (1, 2, 'Время Past Perfect Continious', 4);
INSERT INTO tests(student_id, course_id, topic, score) VALUES (1, 3, 'Фразовые главголы', 5);
INSERT INTO tests(student_id, course_id, topic, score) VALUES (2, 1, 'Формы глагола to be', 3);
INSERT INTO tests(student_id, course_id, topic, score) VALUES (3, 1, 'Формы глагола to be', 3);
INSERT INTO tests(student_id, course_id, topic, score) VALUES (4, 1, 'Формы глагола to be', 5);
INSERT INTO tests(student_id, course_id, topic, score) VALUES (7, 6, 'Основы языка', 4);

INSERT INTO feedbacks(student_id, course_id, score, text) VALUES (1, 2, 4, 'В целом хороший курс, преподаватель понятно объясняет. Но порой бывает сложно понять тему.');
INSERT INTO feedbacks(student_id, course_id, score, text) VALUES (1, 3, 5, 'Все супер!!!');
INSERT INTO feedbacks(student_id, course_id, score, text) VALUES (5, 4, 3, 'Очень тяжело по данному курсу выучить немецкий язык с нуля :(');